# Numpy Exercise Solution  <img src = "numpy1.png">
###### Authored by 

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [3]:
import numpy as np

np.random.randint(10, 37, size=(37,))

array([10, 25, 18, 12, 20, 27, 24, 17, 12, 35, 28, 14, 21, 15, 19, 20, 20,
       22, 26, 13, 23, 33, 27, 24, 31, 35, 10, 25, 15, 26, 17, 32, 16, 30,
       32, 29, 10])

#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [14]:
np.arange(1, 50, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [15]:
np.arange(4, 7, 1/9)

array([4.        , 4.11111111, 4.22222222, 4.33333333, 4.44444444,
       4.55555556, 4.66666667, 4.77777778, 4.88888889, 5.        ,
       5.11111111, 5.22222222, 5.33333333, 5.44444444, 5.55555556,
       5.66666667, 5.77777778, 5.88888889, 6.        , 6.11111111,
       6.22222222, 6.33333333, 6.44444444, 6.55555556, 6.66666667,
       6.77777778, 6.88888889])

#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [19]:
np.round(np.random.random(size = (5,4)),2)

array([[0.77, 0.66, 0.35, 0.46],
       [0.93, 0.97, 0.87, 0.62],
       [0.69, 0.88, 0.47, 0.43],
       [0.89, 0.29, 0.71, 0.89],
       [0.13, 0.86, 0.92, 0.02]])

#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [20]:
np.random.randint(5, 16, size = (5, 5))

array([[14, 11,  6,  6,  9],
       [ 5,  8, 12, 11, 11],
       [ 9, 12,  7,  6,  5],
       [ 5, 15,  9, 12,  8],
       [13, 12,  6,  9, 14]])

#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [25]:
np.zeros((np.random.randint(20), ), dtype = np.int32)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [41]:
np.ones((np.random.randint(100), np.random.randint(100)), dtype = np.float32)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [43]:
matrix = np.array([[9,25,50,34,45],
                  [3,34,34,65,2],
                  [5,7,3,76,3],
                  [7,8,6,54,6],
                  [23,12,8,5,8]])
matrix

array([[ 9, 25, 50, 34, 45],
       [ 3, 34, 34, 65,  2],
       [ 5,  7,  3, 76,  3],
       [ 7,  8,  6, 54,  6],
       [23, 12,  8,  5,  8]])

In [44]:
matrix.shape

(5, 5)

In [45]:
type(matrix)

numpy.ndarray

In [49]:
matrix.dtype

dtype('int32')

#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [117]:
# Solution
matrix[matrix.shape[0]//2, matrix.shape[1]//2]

3

#### 10. Print the all the elements of 3rd row of the matrix

In [54]:
# Solution
matrix[2]

array([ 5,  7,  3, 76,  3])

#### 11. Print the all the elements of 4th columns of the matrix

In [55]:
# Solution
matrix[:, 3]

array([34, 65, 76, 54,  5])

#### 12. Print the 4 corner pixels of the matrix

In [56]:
# Solution
matrix[0,0], matrix[0,4], matrix[4,0], matrix[4,4]

(9, 45, 23, 8)

#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [62]:
# Solution 
m1 = matrix[0:2, 2:4]
m1

array([[50, 34],
       [34, 65]])

In [64]:
m2 = matrix[3:, 0:2]
m2

array([[ 7,  8],
       [23, 12]])

In [65]:
m3 = matrix[2:, 2:]
m3

array([[ 3, 76,  3],
       [ 6, 54,  6],
       [ 8,  5,  8]])

#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [71]:
m1.reshape(-1)

array([50, 34, 34, 65])

In [72]:
m2.reshape(-1)

array([ 7,  8, 23, 12])

In [73]:
m3.reshape(-1)

array([ 3, 76,  3,  6, 54,  6,  8,  5,  8])

#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [79]:
# Concatenate in vertical direction
np.concatenate((m1, m2))

array([[50, 34],
       [34, 65],
       [ 7,  8],
       [23, 12]])

In [80]:
np.concatenate((m1, m2), axis = 1) # Concatenate in horizontal direction

array([[50, 34,  7,  8],
       [34, 65, 23, 12]])

#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [81]:
# Adding
m1 + m2

array([[57, 42],
       [57, 77]])

#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [82]:
# Substracting
m1 - m2

array([[43, 26],
       [11, 53]])

In [83]:
# Multiplying
m1*m2

array([[350, 272],
       [782, 780]])

In [84]:
# Dividing
m1/m2

array([[7.14285714, 4.25      ],
       [1.47826087, 5.41666667]])

#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [87]:
# Solution

m4 = np.array([m1[0], m1[1], [np.mean(m1[:,0]), np.mean(m1[:,1])]])
m4

array([[50. , 34. ],
       [34. , 65. ],
       [42. , 49.5]])

#### 19. Perform the matrix multiplication between m3 and m4

In [91]:
# Solution
M = m3.dot(m4)
M

array([[2860. , 5190.5],
       [2388. , 4011. ],
       [ 906. ,  993. ]])

#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [100]:
# Solution
meanFirstRow = np.mean(M[0])
meanSecondRow = np.mean(M[1])
varianceFirstRow = np.var(M[0])
varianceSecondRow = np.var(M[1])
stdFirstRow = np.std(M[0])
stdSecondRow = np.std(M[1])
mn = min(meanFirstRow, meanSecondRow, varianceFirstRow, varianceSecondRow, stdFirstRow, stdSecondRow)
mx = max(meanFirstRow, meanSecondRow, varianceFirstRow, varianceSecondRow, stdFirstRow, stdSecondRow)

print(f'Minimum value is {mn}')
print(f'Maximum value is {mx}')

Minimum value is 811.5
Maximum value is 1357807.5625


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [102]:
marks = np.array([65,84,47,56,89,98,48,77,80,39])
failed = 0
passed = 0

for n in marks:
    if n < 50:
        failed += 1
    else:
        passed += 1
print(f'The number of student who failed is {failed}')
print(f'The number of student who passed is {passed}')

The number of student who failed is 3
The number of student who passed is 7


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [116]:
adjustedMarks = []
for mark in marks:
    if mark>= 45 and mark<=49 or mark >= 80:
        mark += 5
   
    if mark > 100:
        mark = 100
    adjustedMarks.append(mark)
adjustedMarks

adjustedFailed = 0
adjustedPassed = 0

for n in adjustedMarks:
    if n < 50:
        adjustedFailed += 1
    else:
        adjustedPassed += 1
        
print(f'The increase in the pass percentage is {(adjustedPassed - passed)/len(marks):.2%}')

The increase in the pass percentage is 20.00%


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

#### 25. Create a Github account and upload your solution with the short write-up on Numpy